jms_security_extra:
    secure_all_services: false
    expressions: true


security:
    encoders:
        Ghost\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        ghost_user:
            entity: { class: Ghost\UserBundle\Entity\User, property: username }

    acl:
        connection: default

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /
            anonymous: true

    access_control:
        - { path: ^/topic/new, roles: ROLE_USER }
        - { path: ^/topic/edit, roles: ROLE_USER }
        - { path: ^/topic/delete, roles: ROLE_USER }
        - { path: ^/post/new, roles: ROLE_USER }
        - { path: ^/post/edit, roles: ROLE_USER }
        - { path: ^/post/delete, roles: ROLE_USER }