jms_security_extra:
    secure_all_services: false
    expressions: true


security:
    encoders:
        Ghost\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        ghost_user:
            entity: { class: Ghost\UserBundle\Entity\User, property: username }

    acl:
        connection: default

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/user/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /user/login_check
                login_path: /user/login
            logout:
                path:   /user/logout
                target: /
            anonymous: true

    access_control:
#        - { path: ^/topic/\d+, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
